version: 3

vars:
  APP_NAME: TaskTracker
  SRC: ./cmd/server
  BIN: ./bin/{{.APP_NAME}}.exe


tasks:
  build:
    desc: Builds the Task Tracker app
    sources:
      - "**/*.go"
    generates:
      - "{{.BIN}}"
    cmds:
      - task: clean
      - echo "Building {{.APP_NAME}}"
      - go build -o {{.BIN}} {{.SRC}}
  run:
    desc: Runs the Task Tracker app
    deps:
      - build
    cmds:
      - echo "Running {{.APP_NAME}}"
      - "{{.BIN}}"
  clean:
    desc: Removes previous build bin files
    cmds:
      - echo "Cleaning previous build"
      - mkdir -p ./bin
      - rm -rf ./bin/*