version: 3

includes:
  account: ./account
  task-tracker: ./tasker

tasks:
  run:
    desc: Runs all services
    cmds:
      - task: account:run
      - task: task-tracker:run
  clean:
    desc: Removes previous build bin files
    cmds:
      - echo "Cleaning previous build fully"
      - mkdir -p ./bin
      - rm -rf ./bin/*
  test:
    desc: Runs every _test.go files
    cmds:
      - task: account:test
      - task: task-tracker:test
