-- default database creation for new services
-- CREATE DATABASE ${DB_NAME};
-- CREATE USER ${DB_USER} WITH PASSWORD ${DB_PASSWORD};
-- GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER};
-- \c ${DB_NAME}
-- GRANT USAGE ON SCHEMA public TO ${DB_USER};
-- GRANT CREATE ON SCHEMA public TO ${DB_USER};

-- Account Database creation
CREATE DATABASE ${ACCOUNT_DB_NAME};
CREATE USER ${ACCOUNT_DB_USER} WITH PASSWORD ${ACCOUNT_DB_PASSWORD};
GRANT CONNECT ON DATABASE ${ACCOUNT_DB_NAME} TO ${ACCOUNT_DB_USER};
\c ${ACCOUNT_DB_NAME}
GRANT USAGE ON SCHEMA public TO ${ACCOUNT_DB_USER};
GRANT CREATE ON SCHEMA public TO ${ACCOUNT_DB_USER};


-- Tasker Database creation
CREATE USER ${TASKER_DB_USER} WITH PASSWORD ${TASKER_DB_PASSWORD};
CREATE DATABASE ${TASKER_DB_NAME};
GRANT CONNECT ON DATABASE ${TASKER_DB_NAME} TO ${TASKER_DB_USER};
\c ${TASKER_DB_NAME}
GRANT USAGE ON SCHEMA public TO ${TASKER_DB_USER};
GRANT CREATE ON SCHEMA public TO ${TASKER_DB_USER};